// src/components/views/OnboardingView.vue
<template>
  <div class="onboarding">
    <button class="btn-start" @click="showModal = true">시작하기</button>

    <AuthModal v-if="showModal" @close="showModal = false" />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import AuthModal from '@/components/auth/AuthModal.vue';

const showModal = ref(false);
</script>

// src/components/views/OnboardingView.jsx
import React, { useState } from 'react';
import AuthModal from '@/components/auth/AuthModal';
import '@/assets/styles/onboarding.css';

export default function OnboardingView() {
  const [showModal, setShowModal] = useState(false);

  return (
    <div className="onboarding">
      <button className="btn-start" onClick={() => setShowModal(true)}>
        시작하기
      </button>

      {showModal && <AuthModal onClose={() => setShowModal(false)} />}
    </div>
  );
}
