// src/components/auth/AuthModal.jsx
import React, { useState } from 'react';
import BaseModal from '@/components/common/BaseModal';
import LoginForm from '@/components/auth/LoginForm';
import SignupForm from '@/components/auth/SignupForm';

export default function AuthModal({ onClose }) {
  const [mode, setMode] = useState('login');

  return (
    <BaseModal
      title={mode === 'login' ? '로그인' : '회원가입'}
      onClose={onClose}
    >
      {mode === 'login' ? (
        <LoginForm onSwitch={() => setMode('signup')} onSuccess={onClose} />
      ) : (
        <SignupForm onSwitch={() => setMode('login')} />
      )}
    </BaseModal>
  );
}

// src/components/auth/AuthModal.vue
<template>
  <BaseModal
    :title="mode === 'login' ? '로그인' : '회원가입'"
    @close="$emit('close')"
  >
    <LoginForm
      v-if="mode === 'login'"
      @switch="mode = 'signup'"
      @success="$emit('close')"
    />
    <SignupForm v-else @switch="mode = 'login'" />
  </BaseModal>
</template>

<script setup>
import { ref } from 'vue';
import BaseModal from '@/components/common/BaseModal.vue';
import LoginForm from '@/components/auth/LoginForm.vue';
import SignupForm from '@/components/auth/SignupForm.vue';

const emit = defineEmits(['close']);
const mode = ref('login'); // 'login' | 'signup'
</script>
